apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
data:
  exchange_api_key: NzVlZWVkMWM1MTAxNjc0YmEwYjNlOWMx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coin-master-deployment
  labels:
    app: coin-master-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coin-master-api
  template:
    metadata:
      name: coin-master-api
      labels:
            run: coin-master-api
            app: coin-master-api
    spec:
      containers:
      - name: coin-master-api
        image: guyseaneden/coin-master-api
        ports:
        - containerPort: 8000
        env:
          - name: EXCHANGE_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-key
                key: exchange_api_key
          - name: EXCHANGE_BASE_URL
            value: "https://v6.exchangerate-api.com"


---

apiVersion: v1
kind: Service
metadata:
  name: coin-master-api-internal-service
  labels:
        run: coin-master-api-internal-service
spec:
  type: ClusterIP
  selector:
    app: coin-master-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000


---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: coin-master-api-ingress
spec:
  rules:
  - host: coin-master-api.com
    http:
      paths:
        - path: /
          backend:
            serviceName: coin-master-api-internal-service
            servicePort: 80
  ingressClassName: nginx

