apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: coin-elastic
spec:
  version: 8.1.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false

---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: coin-kibana
spec:
  version: 8.1.3
  count: 1
  elasticsearchRef:
    name: coin-elastic